nano=38000
volume=log
local-ip=172.22.0.210
prometheusMode=pull
prometheusPushTimeOut=10
prometheusPushAddr=127.0.0.1:7676
prometheusPort=8088
trace=stop
external-fqdn=172.22.0.210
pod_name=E2TERM_POD_NAME
sctp-port=36421
