apiVersion: v1
kind: Namespace
metadata:
  name: 5g-core
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    oran.stack/managed-by: nephio
---
apiVersion: v1
kind: Namespace
metadata:
  name: near-rt-ric
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    oran.stack/managed-by: nephio
---
apiVersion: v1
kind: Namespace
metadata:
  name: ran
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    oran.stack/managed-by: nephio
---
apiVersion: v1
kind: Namespace
metadata:
  name: ricxapp
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    oran.stack/managed-by: nephio
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    oran.stack/managed-by: nephio
---
apiVersion: v1
kind: Namespace
metadata:
  name: oran-verify
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    oran.stack/managed-by: nephio
