"""
xapp-kpi — xapps/kpi/kpi.py
============================
TCP server that accepts JSON flow-feature records from any number of ADS
sidecar containers, applies the FHE preprocessor + client-side encryption,
and publishes the encrypted payload onto the Redis Stream `xapp:messages`
with status=0 (pending inference).

A second thread polls the same stream for entries with status=2
(decryption done by xapp-kpi after xapp-inference sets status=1), decrypts
the FHE result, computes the anomaly flag, and updates the stream entry.

Redis Stream schema (one entry per flow):
  id                          – auto-generated by XADD
  sst                         – S-NSSAI SST (string)
  sd                          – S-NSSAI SD  (string)
  encrypted_input             – base64-encoded FHE ciphertext
  encrypted_prediction_result – base64-encoded FHE result  (set by xapp-inference)
  anomaly_percentage          – "0" or "1"                 (set here after decrypt)
  status                      – "0" pending / "1" inferred / "2" decrypted
  timestamp                   – ISO-8601 string

Environment variables:
  KPI_PORT      TCP port to listen on (default: 8080)
  REDIS_HOST    Redis host            (default: ric-dbaas)
  REDIS_PORT    Redis port            (default: 6379)
  MODEL_PATH    FHE model directory   (default: /tmp/fhe_model)
  PREPROCESSOR  Preprocessor pickle   (default: /model/preprocessor.pkl)
  STREAM_KEY    Redis stream name     (default: xapp:messages)
  POLL_INTERVAL Seconds between polls (default: 1)
  KEY_DIR       Shared volume for FHE keys (default: None = in-memory)
"""

import base64
import json
import logging
import os
import pickle
import socket
import sys
import threading
import time
from datetime import datetime, timezone

import pandas as pd
import redis
from concrete.ml.deployment import FHEModelClient

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
KPI_PORT      = int(os.environ.get("KPI_PORT",      "8080"))
REDIS_HOST    = os.environ.get("REDIS_HOST",         "ric-dbaas")
REDIS_PORT    = int(os.environ.get("REDIS_PORT",     "6379"))
MODEL_PATH    = os.environ.get("MODEL_PATH",         "/tmp/fhe_model")
PREPROCESSOR  = os.environ.get("PREPROCESSOR",       "/model/preprocessor.pkl")
STREAM_KEY    = os.environ.get("STREAM_KEY",         "xapp:messages")
POLL_INTERVAL = float(os.environ.get("POLL_INTERVAL","1"))
KEY_DIR       = os.environ.get("KEY_DIR",             None)  # shared volume for FHE keys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [xapp-kpi] %(levelname)s %(message)s",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def b64enc(b: bytes) -> str:
    return base64.b64encode(b).decode()

def b64dec(s: str | bytes) -> bytes:
    if isinstance(s, bytes):
        s = s.decode()
    return base64.b64decode(s)

def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Global resources (populated in main())
# ---------------------------------------------------------------------------
_redis: redis.Redis | None = None
_fhe_client: FHEModelClient | None = None
_preprocessor = None


def _redis_connect() -> redis.Redis:
    while True:
        try:
            r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, decode_responses=False)
            r.ping()
            log.info("Connected to Redis at %s:%d", REDIS_HOST, REDIS_PORT)
            return r
        except redis.exceptions.ConnectionError as exc:
            log.warning("Redis not ready (%s). Retrying in 3s…", exc)
            time.sleep(3)


# ---------------------------------------------------------------------------
# ADS connection handler — runs per accepted TCP connection in its own thread
# ---------------------------------------------------------------------------

def handle_ads(conn: socket.socket, addr: tuple) -> None:
    log.info("ADS connected from %s", addr)
    try:
        with conn, conn.makefile("r") as fobj:
            for raw_line in fobj:
                line = raw_line.strip()
                if not line:
                    continue
                _process_flow(line)
    except OSError as exc:
        log.warning("ADS %s disconnected: %s", addr, exc)
    finally:
        log.info("ADS %s handler exiting.", addr)


def _process_flow(line: str) -> None:
    """Parse one JSON flow record, encrypt it, push to Redis Stream."""
    try:
        flow = json.loads(line)
        sst = int(flow["sst"])
        sd  = int(flow["sd"])
        df  = pd.DataFrame([flow])
        df_model = df.drop(columns=["sst", "sd"])

        model_input = _preprocessor.transform(df_model).toarray()
        enc_input   = _fhe_client.quantize_encrypt_serialize(model_input)

        _redis.xadd(STREAM_KEY, {
            "sst":             str(sst),
            "sd":              str(sd),
            "encrypted_input": b64enc(enc_input),
            "encrypted_prediction_result": "",
            "anomaly_percentage": "",
            "status":          "0",
            "timestamp":       now_iso(),
        })
        log.info("Enqueued flow sst=%d sd=%d → stream %s", sst, sd, STREAM_KEY)

    except json.JSONDecodeError:
        log.error("Invalid JSON from ADS: %s", line[:120])
    except KeyError as exc:
        log.error("Missing key in flow record: %s", exc)
    except Exception as exc:
        log.exception("Unexpected error processing flow: %s", exc)


# ---------------------------------------------------------------------------
# Decrypt thread — polls for status=1 entries and finalises them
# ---------------------------------------------------------------------------

def decrypt_loop() -> None:
    """
    Polls the Redis Stream for entries where status == "1"
    (inference done by xapp-inference), decrypts the result,
    writes anomaly_percentage, and sets status=2.
    """
    log.info("Decrypt thread started.")
    while True:
        try:
            # Read all entries in the stream; small deployment so COUNT=1000 is fine
            entries = _redis.xrange(STREAM_KEY, count=1000)
            for entry_id, fields in entries:
                status = fields.get(b"status", b"").decode()
                if status != "1":
                    continue

                enc_result_b64 = fields.get(b"encrypted_prediction_result", b"")
                if not enc_result_b64:
                    continue

                try:
                    enc_bytes = b64dec(enc_result_b64)
                    result = _fhe_client.deserialize_decrypt_dequantize(enc_bytes)
                    # result shape: [[prob_normal, prob_anomaly]]
                    anomaly_flag = 1 if result[0][1] > 0.95 else 0

                    # Update the stream entry via XDEL + XADD to preserve fields
                    # (Redis Streams don't support in-place field update)
                    all_fields = dict(fields)
                    all_fields[b"anomaly_percentage"] = str(anomaly_flag).encode()
                    all_fields[b"status"]             = b"2"
                    # Decode all keys/values to str for re-insertion
                    new_fields = {
                        k.decode() if isinstance(k, bytes) else k:
                        v.decode() if isinstance(v, bytes) else v
                        for k, v in all_fields.items()
                    }
                    _redis.xdel(STREAM_KEY, entry_id)
                    _redis.xadd(STREAM_KEY, new_fields)
                    log.info("Decrypted entry %s → anomaly=%d", entry_id, anomaly_flag)

                except Exception as exc:
                    log.error("Decrypt error for entry %s: %s", entry_id, exc)

        except Exception as exc:
            log.error("Decrypt loop error: %s", exc)

        time.sleep(POLL_INTERVAL)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    global _redis, _fhe_client, _preprocessor

    # Load preprocessor
    log.info("Loading preprocessor from %s", PREPROCESSOR)
    try:
        with open(PREPROCESSOR, "rb") as f:
            _preprocessor = pickle.load(f)
    except Exception as exc:
        log.error("Cannot load preprocessor: %s", exc)
        sys.exit(1)

    # Load FHE client
    log.info("Loading FHE client from %s", MODEL_PATH)
    try:
        _fhe_client = FHEModelClient(MODEL_PATH, key_dir=KEY_DIR)
    except Exception as exc:
        log.error("Cannot load FHE client: %s", exc)
        sys.exit(1)

    # Connect to Redis
    _redis = _redis_connect()

    # Start decrypt thread
    t_decrypt = threading.Thread(target=decrypt_loop, daemon=True)
    t_decrypt.start()

    # TCP server — accept multiple ADS connections
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind(("0.0.0.0", KPI_PORT))
    srv.listen(16)
    log.info("Listening for ADS connections on 0.0.0.0:%d", KPI_PORT)

    try:
        while True:
            conn, addr = srv.accept()
            t = threading.Thread(target=handle_ads, args=(conn, addr), daemon=True)
            t.start()
    except KeyboardInterrupt:
        log.info("Shutting down.")
    finally:
        srv.close()


if __name__ == "__main__":
    main()
