################################################################################
# BSF Configuration
# Binding Support Function - Manages binding information for users
################################################################################

global:
  max_ue: 4096
  pool:
    packet: 32768

bsf:
  sbi:
    server:
      - address: 172.20.0.15
        port: 7777
    client:
      nrf:
        - uri: http://172.20.0.10:7777
      scp:
        - uri: http://172.20.0.200:7777

db_uri: ${MONGODB_URI}

logger:
  file: /var/log/open5gs/bsf.log
  level: ${LOG_LEVEL}
