################################################################################
# MME Configuration
# Mobility Management Entity - 4G equivalent of AMF
################################################################################

logger:
  file:
    path: /var/log/open5gs/mme.log
  level: ${LOG_LEVEL}

global:
  max:
    ue: 4096

mme:
  freeDiameter: /open5gs/install/etc/freeDiameter/mme.conf
  s1ap:
    server:
      - address: 172.20.0.2
  gtpc:
    server:
      - address: 172.20.0.2
    client:
      sgwc:
        - address: 172.20.0.3
      smf:
        - address: 172.20.0.4
  metrics:
    server:
      - address: 172.20.0.2
        port: 9090
  gummei:
    - plmn_id:
        mcc: ${MCC}
        mnc: ${MNC}
      mme_gid: ${MME_GID}
      mme_code: ${MME_CODE}
  tai:
    - plmn_id:
        mcc: ${MCC}
        mnc: ${MNC}
      tac: ${TAC}
  security:
    integrity_order: [ EIA2, EIA1, EIA0 ]
    ciphering_order: [ EEA0, EEA1, EEA2 ]

db_uri: ${MONGODB_URI}
