################################################################################
# UPF Configuration
# User Plane Function - Forwards data packets between UEs and data networks
################################################################################

global:
  max_ue: 4096
  pool:
    packet: 32768

upf:
  pfcp:
    server:
      - address: 172.20.0.7
        port: 8805
  gtpu:
    server:
      - address: 172.20.0.7
        port: 2152
  session:
    - subnet: ${SMF_SUBNET4}
    - subnet: ${SMF_SUBNET6}
  metrics:
    server:
      - address: 172.20.0.7
        port: 9090

logger:
  file: /var/log/open5gs/upf.log
  level: ${LOG_LEVEL}
