"PlatformComponents":
  - "name": "E2TERM"
    "fqdn": "ric-e2term"
    "port": 38000
  - "name": "SUBMAN"
    "fqdn": "ric-submgr"
    "port": 4560
  - "name": "E2MAN"
    "fqdn": "ric-e2mgr"
    "port": 3801
"local":
  "host": ":8989"
"logger":
  "level": 3
"rmr":
  "protPort": "tcp:4560"
  "maxSize": 2072
  "numWorkers": 1
"RTFILE": "/db/rt.json"
"NBIURL": "http://ric-e2mgr:3800"
